-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object.Info exposing (description, icon, snippets, title, type_)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


type_ : SelectionSet (Maybe String) Tour.Object.Info
type_ =
    Object.selectionForField "(Maybe String)" "_type" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Tour.Object.Info
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


icon : SelectionSet (Maybe String) Tour.Object.Info
icon =
    Object.selectionForField "(Maybe String)" "icon" [] (Decode.string |> Decode.nullable)


snippets : SelectionSet decodesTo Tour.Union.Snippet -> SelectionSet (Maybe (List (Maybe decodesTo))) Tour.Object.Info
snippets object_ =
    Object.selectionForCompositeField "snippets" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


title : SelectionSet (Maybe String) Tour.Object.Info
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
