-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object.Place exposing (address_components, description, formatted_address, formatted_phone_number, icon, lat, lng, name, rating, reference, title, type_, types, url, vicinity)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


type_ : SelectionSet (Maybe String) Tour.Object.Place
type_ =
    Object.selectionForField "(Maybe String)" "_type" [] (Decode.string |> Decode.nullable)


address_components : SelectionSet (Maybe String) Tour.Object.Place
address_components =
    Object.selectionForField "(Maybe String)" "address_components" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Tour.Object.Place
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


formatted_address : SelectionSet (Maybe String) Tour.Object.Place
formatted_address =
    Object.selectionForField "(Maybe String)" "formatted_address" [] (Decode.string |> Decode.nullable)


formatted_phone_number : SelectionSet (Maybe String) Tour.Object.Place
formatted_phone_number =
    Object.selectionForField "(Maybe String)" "formatted_phone_number" [] (Decode.string |> Decode.nullable)


icon : SelectionSet (Maybe String) Tour.Object.Place
icon =
    Object.selectionForField "(Maybe String)" "icon" [] (Decode.string |> Decode.nullable)


lat : SelectionSet (Maybe String) Tour.Object.Place
lat =
    Object.selectionForField "(Maybe String)" "lat" [] (Decode.string |> Decode.nullable)


lng : SelectionSet (Maybe String) Tour.Object.Place
lng =
    Object.selectionForField "(Maybe String)" "lng" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) Tour.Object.Place
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


rating : SelectionSet (Maybe String) Tour.Object.Place
rating =
    Object.selectionForField "(Maybe String)" "rating" [] (Decode.string |> Decode.nullable)


reference : SelectionSet (Maybe String) Tour.Object.Place
reference =
    Object.selectionForField "(Maybe String)" "reference" [] (Decode.string |> Decode.nullable)


title : SelectionSet (Maybe String) Tour.Object.Place
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


types : SelectionSet (Maybe String) Tour.Object.Place
types =
    Object.selectionForField "(Maybe String)" "types" [] (Decode.string |> Decode.nullable)


url : SelectionSet (Maybe String) Tour.Object.Place
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


vicinity : SelectionSet (Maybe String) Tour.Object.Place
vicinity =
    Object.selectionForField "(Maybe String)" "vicinity" [] (Decode.string |> Decode.nullable)
