-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object.Section exposing (day_date, day_order, is_day, title, uuid)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


day_date : SelectionSet (Maybe Int) Tour.Object.Section
day_date =
    Object.selectionForField "(Maybe Int)" "day_date" [] (Decode.int |> Decode.nullable)


day_order : SelectionSet (Maybe Int) Tour.Object.Section
day_order =
    Object.selectionForField "(Maybe Int)" "day_order" [] (Decode.int |> Decode.nullable)


is_day : SelectionSet (Maybe Bool) Tour.Object.Section
is_day =
    Object.selectionForField "(Maybe Bool)" "is_day" [] (Decode.bool |> Decode.nullable)


title : SelectionSet String Tour.Object.Section
title =
    Object.selectionForField "String" "title" [] Decode.string


uuid : SelectionSet String Tour.Object.Section
uuid =
    Object.selectionForField "String" "uuid" [] Decode.string
