-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object.Transportation exposing (booked_through, carrier, confirmation, currency, day, duration, ends_at, notes, phone_number, price, section_id, snippets, starts_at, title, type_, uuid)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


type_ : SelectionSet String Tour.Object.Transportation
type_ =
    Object.selectionForField "String" "_type" [] Decode.string


booked_through : SelectionSet (Maybe String) Tour.Object.Transportation
booked_through =
    Object.selectionForField "(Maybe String)" "booked_through" [] (Decode.string |> Decode.nullable)


carrier : SelectionSet (Maybe String) Tour.Object.Transportation
carrier =
    Object.selectionForField "(Maybe String)" "carrier" [] (Decode.string |> Decode.nullable)


confirmation : SelectionSet (Maybe String) Tour.Object.Transportation
confirmation =
    Object.selectionForField "(Maybe String)" "confirmation" [] (Decode.string |> Decode.nullable)


currency : SelectionSet (Maybe String) Tour.Object.Transportation
currency =
    Object.selectionForField "(Maybe String)" "currency" [] (Decode.string |> Decode.nullable)


day : SelectionSet (Maybe Int) Tour.Object.Transportation
day =
    Object.selectionForField "(Maybe Int)" "day" [] (Decode.int |> Decode.nullable)


duration : SelectionSet (Maybe Int) Tour.Object.Transportation
duration =
    Object.selectionForField "(Maybe Int)" "duration" [] (Decode.int |> Decode.nullable)


ends_at : SelectionSet (Maybe Float) Tour.Object.Transportation
ends_at =
    Object.selectionForField "(Maybe Float)" "ends_at" [] (Decode.float |> Decode.nullable)


notes : SelectionSet (Maybe String) Tour.Object.Transportation
notes =
    Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)


phone_number : SelectionSet (Maybe String) Tour.Object.Transportation
phone_number =
    Object.selectionForField "(Maybe String)" "phone_number" [] (Decode.string |> Decode.nullable)


price : SelectionSet (Maybe Int) Tour.Object.Transportation
price =
    Object.selectionForField "(Maybe Int)" "price" [] (Decode.int |> Decode.nullable)


section_id : SelectionSet String Tour.Object.Transportation
section_id =
    Object.selectionForField "String" "section_id" [] Decode.string


snippets : SelectionSet decodesTo Tour.Union.Snippet -> SelectionSet (Maybe (List (Maybe decodesTo))) Tour.Object.Transportation
snippets object_ =
    Object.selectionForCompositeField "snippets" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


starts_at : SelectionSet (Maybe Float) Tour.Object.Transportation
starts_at =
    Object.selectionForField "(Maybe Float)" "starts_at" [] (Decode.float |> Decode.nullable)


title : SelectionSet (Maybe String) Tour.Object.Transportation
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


uuid : SelectionSet String Tour.Object.Transportation
uuid =
    Object.selectionForField "String" "uuid" [] Decode.string
