-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object.Trip exposing (description, download_pdf, events, messaging, name, overview_map, price, start_at, status, uuid)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


description : SelectionSet (Maybe String) Tour.Object.Trip
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


download_pdf : SelectionSet (Maybe Bool) Tour.Object.Trip
download_pdf =
    Object.selectionForField "(Maybe Bool)" "download_pdf" [] (Decode.bool |> Decode.nullable)


events : SelectionSet decodesTo Tour.Union.Event -> SelectionSet (List decodesTo) Tour.Object.Trip
events object_ =
    Object.selectionForCompositeField "events" [] object_ (identity >> Decode.list)


messaging : SelectionSet (Maybe Bool) Tour.Object.Trip
messaging =
    Object.selectionForField "(Maybe Bool)" "messaging" [] (Decode.bool |> Decode.nullable)


name : SelectionSet String Tour.Object.Trip
name =
    Object.selectionForField "String" "name" [] Decode.string


overview_map : SelectionSet (Maybe Bool) Tour.Object.Trip
overview_map =
    Object.selectionForField "(Maybe Bool)" "overview_map" [] (Decode.bool |> Decode.nullable)


price : SelectionSet (Maybe String) Tour.Object.Trip
price =
    Object.selectionForField "(Maybe String)" "price" [] (Decode.string |> Decode.nullable)


start_at : SelectionSet (Maybe String) Tour.Object.Trip
start_at =
    Object.selectionForField "(Maybe String)" "start_at" [] (Decode.string |> Decode.nullable)


status : SelectionSet Int Tour.Object.Trip
status =
    Object.selectionForField "Int" "status" [] Decode.int


uuid : SelectionSet String Tour.Object.Trip
uuid =
    Object.selectionForField "String" "uuid" [] Decode.string
