-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Object exposing (Activity(..), Cruise(..), Dining(..), Flight(..), Info(..), Information(..), Lodging(..), Place(..), SaveEventPayload(..), SaveSectionPayload(..), SaveTripPayload(..), Section(..), Transportation(..), Trip(..), User(..))


type Activity
    = Activity


type Cruise
    = Cruise


type Dining
    = Dining


type Flight
    = Flight


type Info
    = Info


type Information
    = Information


type Lodging
    = Lodging


type Place
    = Place


type SaveEventPayload
    = SaveEventPayload


type SaveSectionPayload
    = SaveSectionPayload


type SaveTripPayload
    = SaveTripPayload


type Section
    = Section


type Transportation
    = Transportation


type Trip
    = Trip


type User
    = User
