-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Tour.Query exposing (EventRequiredArguments, current_user, event)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Tour.InputObject
import Tour.Interface
import Tour.Object
import Tour.Scalar
import Tour.ScalarCodecs
import Tour.Union


{-| Current Authenticated User
-}
current_user : SelectionSet decodesTo Tour.Object.User -> SelectionSet decodesTo RootQuery
current_user object_ =
    Object.selectionForCompositeField "current_user" [] object_ identity


type alias EventRequiredArguments =
    { uuid : String }


{-| Event type
-}
event : EventRequiredArguments -> SelectionSet decodesTo Tour.Union.Event -> SelectionSet decodesTo RootQuery
event requiredArgs object_ =
    Object.selectionForCompositeField "event" [ Argument.required "uuid" requiredArgs.uuid Encode.string ] object_ identity
